version: '3'

services:

  web:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
    depends_on:
      - redis
      - db

  redis:
    image: redis:alpine

  db:
    image: postgres:alpine
